### ISSUE TITLE
please add tag for snapdragon 0.11.0 release

### ISSUE THREAD

**Issue by pravi** [here-be/snapdragon#10]
tags in this repo is not in sync with npm releases.

**Comment by jonschlinkert** [comment]
![image](https://user-images.githubusercontent.com/383994/34837135-e3db51ba-f6c7-11e7-8f17-7bc7553119b4.png)

**Comment by pravi** [comment]
![image](https://user-images.githubusercontent.com/708222/34837836-1155e8d0-f722-11e7-9788-39e1aabca62f.png)

**Comment by jonschlinkert** [comment]
You need to scroll to the next page. Some tags were added later, so the tags aren't in order.

**Comment by pravi** [comment]
Thanks! It is a bit confusing when latest version is listed in the second page. gitlab has a feature to order tags by tag name but its missing here.
