### ISSUE TITLE
Upgrade source-map-resolve to v0.6.0

### ISSUE THREAD

**Issue by silkfire** [here-be/snapdragon#24]
Could we upgrade the `source-map-resolve` dependency from 0.5.3 to 0.6.0 to get rid of the following deprecation messages:

> npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
> npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated

**Comment by beeman** [comment]
There has been a PR open for more than 2 years with this #13 

@jonschlinkert could you reconsider merging this, maybe just by creating a major release?

**Comment by weslenng** [comment]
> There has been a PR open for more than 2 years with this #13
> 
> @jonschlinkert could you reconsider merging this, maybe just by creating a major release?

```javascript
"source-map" !== "source-map-resolve"
```

**Comment by beeman** [comment]
You are totally right @weslenng - I see you created a PR that does fix the actual issue. Let's hope it gets merged soon 🙏

**Comment by polarathene** [comment]
Looking at the activity of all repos under `here-be`, it doesn't look there's been any development since 2018? What's the likelihood of seeing the PR for this merged? Is the organization no longer active?
