### ISSUE TITLE
upgrade source-map-resolve to 0.6.0

### ISSUE THREAD

**Issue by rubiin** [here-be/snapdragon#27]
source-map-resolve  0.50 uses two deprecated libs urix and resolve-url. so nstalling snapdragon via npm complains about the deprecated warning.

**Comment by Husterknupp** [comment]
see also here: #24

**Comment by KenEucker** [comment]
Bumping this, @doowb can you help us with a dependency update on this package?

**Comment by danez** [comment]
Fixed in 0.12.1
