### ISSUE TITLE
Security Vulnerability pick up by Fortify Scan (snapdragon)

### ISSUE THREAD

**Issue by nekyouto** [here-be/snapdragon#28]
Good Afternoon snapdragon team,

We were performing a scan on the snapdragon Javascript library and the Fortify application has picked up the following items that are discovered as vulnerabilities. 
(Reason being our project has imported this library as a dependency and part of our deliverable would requires the scanning of the full source code and identify/remove the vulnerable.)

(**Low**) Password Management: Password in Comment
No of items picked by the Fortify Scan: **Less than 10**
Kindly refer to the following image, scanImage1.png 
![scanImage1](https://user-images.githubusercontent.com/6581645/117440727-05e02500-af67-11eb-8ebe-e4273894a0c7.png)

Do give us a heads up on when the team is planning to fix these vulnerabilities and/or the possible workarounds to prevent the same items to be picked up by the Fortify Scans again.

**Comment by attritionorg** [comment]
The highlighted line doesn't look like a password in the comments. It is likely firing because it sees /etc/passwd?

**Comment by doowb** [comment]
That code isn't even in this module. It looks like might be from Node's source.
